name: update

on:
  schedule:
    - cron: '0 15 * * SUN'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - name: install packages
        run: yarn install --immutable

      - name: update rules
        run: yarn update-rules

      - name: count changes
        id: changes
        run: |
          git add -N .
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      - name: build
        if: steps.changes.outputs.count > 0
        run: yarn build

      - name: commit and push
        if: steps.changes.outputs.count > 0
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "fix: update the list"
          git push

      - name: release
        if: steps.changes.outputs.count > 0
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn semantic-release
